version: "3.7"
services:
  #
  # mongodb
  #
  database:
    image: mongo:4.4
    env_file:
      .env
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - database:/data/db
    ports:
      - "27017:27017"

volumes:
  database:
